kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: nginx
  namespace: nginx
spec:
  to:
    kind: Service
    name: nginx
    weight: 100
  port:
    targetPort: web
  wildcardPolicy: None
