kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: nginx
  namespace: {{ project_name }}
  annotations:
    description: Nginx
    template.alpha.openshift.io/wait-for-ready: 'true'
  labels:
    app.kubernetes.io/part-of: Nginx
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - nginx
        from:
          kind: ImageStreamTag
          namespace: {{ project_name }}
          name: 'nginx:latest'
        lastTriggeredImage:
    - type: ConfigChange
  replicas: {{ replica_count }}
  revisionHistoryLimit: 10
  selector:
    name: nginx
  template:
    metadata:
      name: nginx
      creationTimestamp: null
      labels:
        name: nginx
    spec:
      containers:
        - resources:
            limits:
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: nginx
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: {{ project_name }}/nginx
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
