kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: nginx
  namespace: {{ project_name }}
  labels:
    app: nginx
    template: nginx
  annotations:
    description: Nginx Frontend Build Configuration
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'nginx:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nginx:1.16-el8'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/sclorg/nginx-ex.git'
      ref: master
  triggers:
    - type: ImageChange
  triggers:
    - type: ConfigChange
  runPolicy: Serial
